"""initial schema

Revision ID: 665d6814648e
Revises: 
Create Date: 2026-08-02 15:34:51.020979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665d6814648e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_skill_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('theta', sa.Float(), nullable=False),
    sa.Column('theta_se', sa.Float(), nullable=False),
    sa.Column('n_responses', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'skill_id', name='uq_skill_state')
    )
    op.create_index(op.f('ix_candidate_skill_state_candidate_id'), 'candidate_skill_state', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_skill_state_skill_id'), 'candidate_skill_state', ['skill_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('framework_version', sa.String(), nullable=False),
    sa.Column('composite_score', sa.Integer(), nullable=True),
    sa.Column('band', sa.String(), nullable=True),
    sa.Column('coverage', sa.Float(), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_results_band'), 'evaluation_results', ['band'], unique=False)
    op.create_index(op.f('ix_evaluation_results_candidate_id'), 'evaluation_results', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_evaluation_results_composite_score'), 'evaluation_results', ['composite_score'], unique=False)
    op.create_index(op.f('ix_evaluation_results_session_id'), 'evaluation_results', ['session_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(), nullable=False),
    sa.Column('a', sa.Float(), nullable=False),
    sa.Column('b', sa.Float(), nullable=False),
    sa.Column('c', sa.Float(), nullable=False),
    sa.Column('n_administered', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_skill'), 'items', ['skill'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('seniority', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('framework_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_responses_candidate_id'), 'item_responses', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_item_responses_item_id'), 'item_responses', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_responses_session_id'), 'item_responses', ['session_id'], unique=False)
    op.create_table('interview_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'seq', name='uq_event_seq')
    )
    op.create_index(op.f('ix_interview_events_session_id'), 'interview_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_events_session_id'), table_name='interview_events')
    op.drop_table('interview_events')
    op.drop_index(op.f('ix_item_responses_session_id'), table_name='item_responses')
    op.drop_index(op.f('ix_item_responses_item_id'), table_name='item_responses')
    op.drop_index(op.f('ix_item_responses_candidate_id'), table_name='item_responses')
    op.drop_table('item_responses')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_items_skill'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_evaluation_results_session_id'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_composite_score'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_candidate_id'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_band'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_candidate_skill_state_skill_id'), table_name='candidate_skill_state')
    op.drop_index(op.f('ix_candidate_skill_state_candidate_id'), table_name='candidate_skill_state')
    op.drop_table('candidate_skill_state')
    # ### end Alembic commands ###
